#!/bin/bash

# ci_pre_xcodebuild.sh
#
# Xcode Cloud pre-build script — runs before xcodebuild (and before xcconfig
# resolution), so any files created here are available to the build system.
#
# Generates ios-app/Secrets.xcconfig from CI secret environment variables.
# The project build configuration references Secrets.xcconfig as its base
# configuration, so Xcode resolves $(DEEPSEEK_API_KEY) and $(MISTRAL_API_KEY)
# from this file into Info.plist at compile time.
#
# Required environment variables (set in Xcode Cloud workflow):
#   DEEPSEEK_API_KEY
#   MISTRAL_API_KEY
#
# If either is missing the script writes an empty value — the app will build
# but API calls at runtime will fail with LLMError.noAPIKey.

set -e

XCCONFIG_DIR="${CI_WORKSPACE:-$(cd "$(dirname "$0")/.." && pwd)}/ios-app"

cat > "${XCCONFIG_DIR}/Secrets.xcconfig" <<EOF
// Secrets.xcconfig — auto-generated by ci_pre_xcodebuild.sh
// DO NOT EDIT — this file is ephemeral and recreated every CI run.

DEEPSEEK_API_KEY = ${DEEPSEEK_API_KEY:-}
MISTRAL_API_KEY = ${MISTRAL_API_KEY:-}
EOF
