import Foundation
import SwiftData

// MARK: - SummaryService

/// Owns all summary generation logic: version tracking, on-demand generation,
/// version-based regeneration, and batch backfill for outdated summaries.
///
/// Deduplication via `inFlight` ensures that concurrent requests for the same
/// date (e.g. batch backfill + calendar tap) don't fire duplicate API calls.
@MainActor
final class SummaryService {
    // MARK: - Version

    /// The current summarizer version. Bump this when the summarizer prompt
    /// or logic changes to trigger regeneration of outdated summaries.
    ///
    /// Start at 0. Existing summaries with `nil` version are treated as v0.
    static let currentVersion = 0

    // MARK: - Dependencies

    private let conversationService: ConversationService
    private let router: ModelRouter

    // MARK: - Dedup

    /// Date keys currently being generated (prevents duplicate API calls).
    private var inFlight: Set<String> = []

    // MARK: - Init

    init(conversationService: ConversationService, router: ModelRouter = ModelRouter()) {
        self.conversationService = conversationService
        self.router = router
    }

    // MARK: - Public API

    /// Returns the existing summary for a date, regardless of version.
    /// Never triggers generation.
    ///
    /// - Parameter dateKey: The date key (e.g. `"2026-06-13"`).
    /// - Returns: The stored summary, or `nil` if none exists.
    func existingSummary(for dateKey: String) -> String? {
        conversationService.loadConversation(dateKey: dateKey)?.summary
    }

    /// Returns the stored version for a date, or 0 if nil.
    ///
    /// - Parameter dateKey: The date key.
    /// - Returns: The version number (0 if nil / unversioned).
    func storedVersion(for dateKey: String) -> Int {
        guard let conv = conversationService.loadConversation(dateKey: dateKey) else { return 0 }
        return conv.summaryVersion ?? 0
    }

    /// Whether the summary for a date is outdated (version < currentVersion).
    ///
    /// - Parameter dateKey: The date key.
    /// - Returns: `true` if a summary exists but was generated by an older version.
    func isOutdated(for dateKey: String) -> Bool {
        storedVersion(for: dateKey) < Self.currentVersion
    }

    /// Whether generation is currently in flight for this date.
    ///
    /// - Parameter dateKey: The date key.
    /// - Returns: `true` if a generation task is active.
    func isGenerationPending(for dateKey: String) -> Bool {
        inFlight.contains(dateKey)
    }

    /// Generates a summary if it's missing (no summary exists yet).
    ///
    /// Skips conversations that are still active (<30 min idle) or empty.
    /// Returns `nil` if the conversation is not ready for summarization
    /// or if generation fails.
    ///
    /// - Parameter dateKey: The date key.
    /// - Returns: The generated summary, or `nil`.
    func generateSummaryIfMissing(for dateKey: String) async -> String? {
        guard let conversation = conversationService.loadConversation(dateKey: dateKey) else { return nil }
        // Skip if already has a summary.
        guard conversation.summary == nil else { return conversation.summary }
        // Skip active conversations (may cross midnight boundary).
        guard !conversation.hasRecentActivity else { return nil }
        // Skip empty conversations.
        guard !conversation.messages.isEmpty else { return nil }
        // Dedup: skip if already being generated.
        if inFlight.contains(dateKey) { return nil }

        return await performGeneration(for: dateKey, conversation: conversation)
    }

    /// Regenerates the summary if it's outdated (version < currentVersion).
    ///
    /// If the conversation is still active, regeneration is skipped.
    /// On failure the old summary is preserved and returned.
    ///
    /// - Parameter dateKey: The date key.
    /// - Returns: The new summary on success, or the existing summary on failure/nil.
    func regenerateIfOutdated(for dateKey: String) async -> String? {
        guard let conversation = conversationService.loadConversation(dateKey: dateKey) else { return nil }
        guard let oldSummary = conversation.summary else { return nil }
        // Already up-to-date.
        guard isOutdated(for: dateKey) else { return oldSummary }
        // Skip active conversations.
        guard !conversation.hasRecentActivity else { return oldSummary }
        // Dedup: if already in flight, return the old summary now.
        if inFlight.contains(dateKey) { return oldSummary }

        let result = await performGeneration(for: dateKey, conversation: conversation)
        return result ?? oldSummary  // Fall back to old summary on failure.
    }

    /// Ensures the conversation has an up-to-date summary.
    ///
    /// Behaviour:
    /// - Summary exists and current version → returned immediately.
    /// - Summary exists but outdated → returned immediately, background regeneration started.
    /// - Summary missing → generated synchronously (caller waits).
    /// - Active / empty conversation → `nil`.
    ///
    /// - Parameter dateKey: The date key.
    /// - Returns: The best available summary text, or `nil`.
    func ensureSummary(for dateKey: String) async -> String? {
        guard let conversation = conversationService.loadConversation(dateKey: dateKey) else { return nil }
        guard !conversation.hasRecentActivity else { return nil }
        guard !conversation.messages.isEmpty else { return nil }

        // Summary exists — check version.
        if let existing = conversation.summary {
            if isOutdated(for: dateKey) {
                // Return old summary immediately, regenerate in background.
                if !inFlight.contains(dateKey) {
                    Task { [weak self] in
                        _ = await self?.regenerateIfOutdated(for: dateKey)
                    }
                }
            }
            return existing
        }

        // No summary — generate now.
        return await performGeneration(for: dateKey, conversation: conversation)
    }

    // MARK: - Batch Backfill

    /// Batch-regenerates outdated summaries for recent days.
    ///
    /// Processes days from most recent to oldest. Each day's regeneration
    /// completes before the next starts. There is a 0.5s delay between calls
    /// to avoid rate limits.
    ///
    /// - Parameter lookbackDays: How many days to scan (default: 30).
    func backfillOldVersions(lookbackDays: Int = 30) async {
        let todayKey = ConversationService.todayDateKey
        let allKeys = conversationService.fetchAllDateKeys()
            .filter { $0 != todayKey }
            .sorted(by: >)  // most recent first

        // Only process up to lookbackDays.
        let recentKeys = Array(allKeys.prefix(lookbackDays))

        for dateKey in recentKeys {
            // Check version: skip if current or already pending.
            guard isOutdated(for: dateKey) || existingSummary(for: dateKey) == nil else { continue }
            guard !inFlight.contains(dateKey) else { continue }

            // Regenerate or generate, best effort.
            if existingSummary(for: dateKey) != nil {
                _ = await regenerateIfOutdated(for: dateKey)
            } else {
                _ = await generateSummaryIfMissing(for: dateKey)
            }

            // Small delay between API calls.
            try? await Task.sleep(nanoseconds: 500_000_000)  // 0.5s
        }
    }

    // MARK: - Private

    /// Performs the actual LLM call and saves the result.
    ///
    /// - Parameters:
    ///   - dateKey: The date key.
    ///   - conversation: The conversation to summarize.
    /// - Returns: The generated summary, or `nil` on failure.
    private func performGeneration(for dateKey: String, conversation: Conversation) async -> String? {
        inFlight.insert(dateKey)
        defer { inFlight.remove(dateKey) }

        let conversationText = conversationService.fetchFullConversationText(dateKey: dateKey) ?? ""
        guard !conversationText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return nil
        }

        let summarySystemPrompt = """
        You are a summarizer. Summarize the following conversation in 2-3 sentences.
        Focus on what the user talked about, how they felt, and any key events or decisions.
        Be concise and factual.
        """

        let summaryRequest: ChatHistory = [
            ChatMessage(role: .system, content: summarySystemPrompt),
            ChatMessage(role: .user, content: conversationText),
        ]

        do {
            let response = try await router.sendMessages(summaryRequest, tier: .cheap)
            if case .text(let summary) = response {
                conversationService.updateSummary(dateKey: dateKey, summary: summary, version: Self.currentVersion)
                print("[SummaryService] Summary saved for \(dateKey): \(summary.prefix(80))...")
                return summary
            }
        } catch {
            print("[SummaryService] Failed to generate summary for \(dateKey): \(error)")
        }
        return nil
    }
}
