#!/bin/sh

# ci_pre_xcodebuild.sh
# Xcode Cloud pre-build script — generates Secrets.xcconfig from CI secrets.
#
# Standard approach documented by Apple:
# https://developer.apple.com/documentation/xcode/writing-custom-build-scripts

set -e

echo "ci_pre_xcodebuild.sh: Generating Secrets.xcconfig..."

# The script lives at <repo_root>/ci_scripts/ci_pre_xcodebuild.sh
# $0 is the path the script was invoked with.
SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
REPO_ROOT=$(dirname "$SCRIPT_DIR")

echo "ci_pre_xcodebuild.sh: REPO_ROOT=${REPO_ROOT}"

cat > "${REPO_ROOT}/Secrets.xcconfig" <<EOF
// Secrets.xcconfig — auto-generated by ci_pre_xcodebuild.sh

DEEPSEEK_API_KEY = ${DEEPSEEK_API_KEY:-}
MISTRAL_API_KEY = ${MISTRAL_API_KEY:-}
EOF

echo "ci_pre_xcodebuild.sh: Done."
